### ISSUE TITLE
Control specific forge pieces in a script

### ISSUE THREAD

**Issue by jackbrookes** [DavidJCobb/ReachVariantEditor#10]
Could anyone point to API reference for how to control specific forge pieces in a script? I.e. set position of a wall, etc, if possible.

**Comment by DavidJCobb** [comment]
You would need to put a gametype label on the desired piece when editing your map in Forge. Then, you can use a [for-each-object-with-label loop](https://davidjcobb.github.io/ReachVariantEditor/script/for.html) to run code for all objects with that label. The `current_object` [object variable](https://davidjcobb.github.io/ReachVariantEditor/script/api/object.html) will hold the object that the code is currently running for.

As for how to actually move objects, there isn't a dedicated "set position" function, nor a "move object in X direction by Y many units" function. The general approach for moving an object by an arbitrary amount would be something like this:

1. [Spawn a Hill Marker near the object](https://davidjcobb.github.io/ReachVariantEditor/script/api/object/actions/place_at_me.html), at the direction and distance that you want.
2. [Attach](https://davidjcobb.github.io/ReachVariantEditor/script/api/object/actions/attach_to.html) the object to the Hill Marker, using (0, 0, 0) as the offset.
3. [Detach](https://davidjcobb.github.io/ReachVariantEditor/script/api/object/actions/detach.html) the object from the Hill Marker.
4. [Delete](https://davidjcobb.github.io/ReachVariantEditor/script/api/object/actions/delete.html) the Hill Marker.

It's a bit janky, but from what I remember, attaching and detaching is the same trick that Bungie used to move one object to another.

**Comment by jackbrookes** [comment]
Thank you I will give it a try!

**Comment by jackbrookes** [comment]
@DavidJCobb I would like to move an object over time, I have everything setup, but seems I can't use a timer object value in setting position. E.g. an example I expected to sawtooth an object across 2m distance:

```
global.number[0] = global.timer[0]
global.number[0] %= 20
example.attach_to(current_object, global.number[0], 0, 0, absolute)
```

Any suggestions?

**Comment by Person123422** [comment]
@jackbrookes use object scaling to move an object a specific distance using a variable. You also have more precise control of the offset you are moving an object with scaling. In this old gametype I allow the user to use spawn squence to control the speed/offset per tick of an object they want to move and hill markers to point in the direction. Also my gametype does some weird stuff on the local trigger to allow non-hosts to see its smooth movement without it spazzing out.
[platform_v2_despawn_issue.zip](https://github.com/DavidJCobb/ReachVariantEditor/files/6174284/platform_v2_despawn_issue.zip)

check out the gametype code and example map to learn how it works.

**Comment by Person123422** [comment]
Also I made it so the platform moves players and objects that are on top of it.

https://streamable.com/xcqthk

**Comment by Person123422** [comment]
Keep in mind non-script made objects will despawn overtime when abandoned.
