### ISSUE TITLE
New 'infinity' gametype icon

### ISSUE THREAD

**Issue by Noble-N9** [DavidJCobb/ReachVariantEditor#14]
There's a new 'infinity' gametype icon that 343 just added in the previous update for their pre-game mode used in the Custom Games Browser. It's not saved as a local or recent gametype (at least in the usual locations) so I wasn't able to grab the .bin to determine the integer index.

Icon can be found here: ui\chud\bitmaps\variant_items\gametypes.bitmap

![pre-game-mcc](https://user-images.githubusercontent.com/26795678/124812088-30336c00-df31-11eb-9670-76faa97c1071.png)

**Comment by DavidJCobb** [comment]
Fixed in v2.1.6.
