### ISSUE TITLE
Scripted option values > 500 causes script to be unloadable in-game

### ISSUE THREAD

**Issue by JonnyOThan** [DavidJCobb/ReachVariantEditor#18]
I was setting up an "oddball count" option and created an "all" option with value 511.  This seems to be the maximum possible game option value.  But MCC did not load the script.  500 works, 501 does not.

**Comment by DavidJCobb** [comment]
Fixed in v2.1.7; the UI no longer allows values above 500. Note that existing files with invalid values may not be retroactively corrected on load.
