### ISSUE TITLE
set_weapon_pickup_priority(hold_action) isn't quite right

### ISSUE THREAD

**Issue by JonnyOThan** [DavidJCobb/ReachVariantEditor#19]
I'm pretty sure this is actually "high" priority - meaning if this weapon and a regular one are next to each other, holding the action button will pick up the one marked high priority.  This is used for flags, oddballs, etc.

**Comment by DavidJCobb** [comment]
Fixed in v2.1.7: the value is now named `high`, with `hold_action` remaining usable (with a deprecation warning) for backward-compatibility.
