### ISSUE TITLE
Unknown bool in the attach action is for the use of absolute orientation.

### ISSUE THREAD

**Issue by Person123422** [DavidJCobb/ReachVariantEditor#3]
https://github.com/DavidJCobb/ReachVariantEditor/blob/f8d30382503f6101586a7dfe717eb48619eb066c/native/src/ReachVariantTool/game_variants/components/megalo/actions.cpp#L355

So if this bool was enabled and you attached an object to an upside down object with z="10" it would attach correctly regardless of the rotation. If it was false the attached object would be above the warthog.

**Comment by DavidJCobb** [comment]
Tested and confirmed. Script API will be amended accordingly.
