### ISSUE TITLE
Useful information about fancy symbols in strings.

### ISSUE THREAD

**Issue by Person123422** [DavidJCobb/ReachVariantEditor#8]
There are many fancy symbols that you can use in strings in a modded gametype. You might want to include these instructions in the documentation. This will allow script authors to take advantage of them.
![Capture](https://user-images.githubusercontent.com/59069249/83375227-32291400-a39c-11ea-8a5e-9199e3f7868f.PNG)
![Halo_ The Master Chief Collection   1_20_2020 9_11_05 PM](https://user-images.githubusercontent.com/59069249/83375253-44a34d80-a39c-11ea-8646-f4b8ea04faaf.png)

Here are the steps to get all these symbols:
1. Download lord zedd's font packager. 
2. Open the file font_package.bin in the halo reach font directory. (haloreach\maps\fonts) 
3. Select tv_nord_hud-15
Simply double click a symbol and paste them into a string and they will show up on waypoint text.
Some of these symbols don't show up on hud widgets. Most symbols in eurostile_It_demi-13 show up in hud widgets.

**Comment by Person123422** [comment]
Link to font packager:
https://github.com/Lord-Zedd/FontPackager/releases

**Comment by DavidJCobb** [comment]
After entirely too long I have finally added this [to the documentation](https://davidjcobb.github.io/ReachVariantEditor/script/string-special-chars.html). Thank you for the original report.
